import React, { FC, useCallback, useEffect, useState } from 'react';
import { useValue } from 'cs2/api';
import { cityInfo, Number2 } from 'cs2/bindings';
import { DraggablePanelProps, PanelProps, Scrollable, Panel, Tooltip } from 'cs2/ui';
import { BuildingDemandData } from '../../bindings';
import { useLocalization } from 'cs2/l10n';
import styles from './Demand.module.scss';
import { Localekeys } from 'mods/locale';

interface DemandSection2Props {
    title: string;
    value: number;
    factors: { factor: string; weight: number }[];
    t: (key: string, fallback: string) => string;
}

// Map factor names to display-friendly names and tooltips
const getDisplayName = (
  factor: string,
  weight: number,
  translate: (key: string, fallback: string) => string
): { display: string; tooltip: string } => {
  // Helper to append the "influence" explanation to each tooltip
  const appendInfluence = (tooltip: string) =>
    tooltip + " " + translate("InfoLoomTwo.DemandPanel[FactorWeightTooltip]", "The greater the number, the more influence this factor has on demand.");

  const displayNames: { [key: string]: { display: string; tooltip: string } } = {
    StorageLevels: {
      display: translate(Localekeys.StorageLevels, "Storage Levels"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[StorageLevelsTooltip]", "Current storage levels for goods and resources. Low storage increases demand."))
    },
    UneducatedWorkforce: {
      display: translate(Localekeys.UneducatedWorkforce, "Labour Availability"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[UneducatedWorkforceTooltip]", "Availability of uneducated workers for entry-level jobs."))
    },
    EducatedWorkforce: {
      display: translate(Localekeys.EducatedWorkforce, "High Skill Labour Availability"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[EducatedWorkforceTooltip]", "Availability of educated workers for skilled jobs."))
    },
    CompanyWealth: {
      display: translate(Localekeys.CompanyWealth, "Company Wealth"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[CompanyWealthTooltip]", "Overall wealth of companies. Wealthier companies may reduce demand for new businesses."))
    },
    LocalDemand: {
      display: translate(Localekeys.LocalDemand, "Local Demand"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[LocalDemandTooltip]", "Demand generated by local population and businesses."))
    },
    Unemployment: {
      display: translate(weight < 0 ? Localekeys.NegativeUnemployment : Localekeys.PositiveUnemployment, "Availability of Jobs"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[UnemploymentTooltip]", "How many jobs are available for citizens. High unemployment increases demand."))
    },
    FreeWorkplaces: {
      display: translate(Localekeys.FreeWorkplaces, "Free Workplaces"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[FreeWorkplacesTooltip]", "Number of available workplaces. More free workplaces can reduce demand for new jobs."))
    },
    Happiness: {
      display: translate(Localekeys.Happiness, "Citizen Happiness"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[HappinessTooltip]", "Overall happiness of citizens. Unhappy citizens increase demand for better housing or jobs."))
    },
    Homelessness: {
      display: translate(Localekeys.Homelessness, "Cost of Living"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[HomelessnessTooltip]", "High homelessness or high cost of living increases demand for affordable housing."))
    },
    TouristDemand: {
      display: translate(Localekeys.TouristDemand, "Tourist Demand"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[TouristDemandTooltip]", "Demand generated by tourists for services, goods, and accommodations."))
    },
    LocalInputs: {
      display: translate(Localekeys.LocalInputs, "Local Inputs"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[LocalInputsTooltip]", "Availability of local input resources for production. Shortages increase demand."))
    },
    Taxes: {
      display: translate(Localekeys.Taxes, "Taxes"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[TaxesTooltip]", "Tax rates for residents and companies. Higher taxes reduce demand."))
    },
    Students: {
      display: translate(Localekeys.StudentsFactor, "Students"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[StudentsTooltip]", "Number of students in the city. More students can affect workforce and housing demand."))
    },
    EmptyBuildings: {
      display: translate(Localekeys.EmptyBuildings, "Building Occupancy"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[EmptyBuildingsTooltip]", "How many buildings are currently empty and available for new residents or businesses."))
    },
    EmptyZones: {
      display: translate(Localekeys.EmptyZones, "Empty Zones"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[EmptyZonesTooltip]", "Amount of zoned land that is currently empty. More empty zones can reduce demand for new zoning."))
    },
    PoorZoneLocation: {
      display: translate(Localekeys.PoorZoneLocation, "Poor Zone Location"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[PoorZoneLocationTooltip]", "Zones in undesirable locations reduce demand for development."))
    },
    PetrolLocalDemand: {
      display: translate(weight < 0 ? Localekeys.NegativePetrol : Localekeys.PositivePetrol,"Gas Station Availability"),
      tooltip: appendInfluence(
        translate(
          weight < 0 ? Localekeys.NegativePetrol : Localekeys.PositivePetrol,
          "Availability of gas stations for local demand."
        )
      )
    },
    Warehouses: {
      display: translate(Localekeys.Warehouses, "Availability of Warehouses"),
      tooltip: appendInfluence(translate("InfoLoomTwo.DemandPanel[WarehousesTooltip]", "How many warehouses are available for industrial or commercial storage needs."))
    },
  };
  return displayNames[factor] || { display: factor, tooltip: translate("InfoLoomTwo.DemandPanel[FactorWeightTooltip]", "The greater the number, the more influence this factor has on demand.") };
};

const DemandSection2: FC<DemandSection2Props> = ({ title, value, factors, t }) => {
    const formatWeight = (weight: number) => ({
        className: weight < 0 ? 'negative_YWY' : 'positive_zrK',
        display: weight,
    });

    return (
        <div className={`infoview-panel-section_RXJ ${styles.sectionContainer}`}>
            <div className="labels_L7Q row_S2v uppercase_RJI">
                <div className={`left_Lgw row_S2v ${styles.sectionTitle}`}>
                  {title}
                </div>
                {value >= 0 && (
                    <div className={`right_k30 row_S2v ${styles.sectionValue}`}>
                        {Math.round(value * 100)}
                    </div>
                )}
            </div>

            <div className={`space_uKL ${styles.spacer}`} />

            {factors.map((item, index) => {
                const { display, tooltip } = getDisplayName(item.factor, item.weight, t);
                const { className, display: weightDisplay } = formatWeight(item.weight);

                return (
                    <div key={index} className={`labels_L7Q row_S2v small_ExK ${styles.factorRow}`}>
                        <Tooltip tooltip={tooltip}>
                            <div className={`left_Lgw row_S2v ${styles.factorLabel}`}>
                                {display}
                            </div>
                        </Tooltip>
                        <div className={`right_k30 row_S2v ${styles.factorValueContainer}`}>
                            <div className={`${className} ${styles.factorValue}`}>
                                {weightDisplay}
                            </div>
                        </div>
                    </div>
                );
            })}
        </div>
    );
};

const $DemandFactors: FC<DraggablePanelProps> = ({ onClose, initialPosition }) => {
  const { translate } = useLocalization();
  // Demand values
  const residentialLowDemand = useValue(cityInfo.residentialLowDemand$);
  const residentialMediumDemand = useValue(cityInfo.residentialMediumDemand$);
  const residentialHighDemand = useValue(cityInfo.residentialHighDemand$);
  const commercialDemand = useValue(cityInfo.commercialDemand$);
  const industrialDemand = useValue(cityInfo.industrialDemand$);
  const officeDemand = useValue(cityInfo.officeDemand$);

  // Demand factors
  const residentialLowFactors = useValue(cityInfo.residentialLowFactors$);
  const residentialMediumFactors = useValue(cityInfo.residentialMediumFactors$);
  const residentialHighFactors = useValue(cityInfo.residentialHighFactors$);
  const commercialFactors = useValue(cityInfo.commercialFactors$);
  const industrialFactors = useValue(cityInfo.industrialFactors$);
  const officeFactors = useValue(cityInfo.officeFactors$);
  const t = (key: string, fallback: string) => translate(key, fallback) ?? fallback;
  // Building demand
  const buildingDemandData = useValue(BuildingDemandData);
  const titles = [
    'Residential Low',
    'Residential Medium',
    'Residential High',
    'Commercial',
    'Industrial',
    'Storage',
    'Office',
  ];
  const buildingDemandFactors = titles.map((factor, index) => ({
    factor,
    weight: buildingDemandData[index] ?? 0,
  }));
  return (
    <Panel
      draggable
      onClose={onClose}
      initialPosition={initialPosition}
      className={styles.panel}
      header={
        <div className={styles.header}>
          <span className={styles.headerText}>{translate(Localekeys.Demand, "Demand")}</span>
        </div>
      }
    >

    <DemandSection2
        title={t(Localekeys.BuildingDemand, "Building demand")}
        value={-1}
        factors={buildingDemandFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.ResLow, "Low Density Residential Demand")}
        value={residentialLowDemand}
        factors={residentialLowFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.ResMedium, "Medium Density Residential Demand")}
        value={residentialMediumDemand}
        factors={residentialMediumFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.ResHigh, "High Density Residential Demand")}
        value={residentialHighDemand}
        factors={residentialHighFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.CommercialDemand, "Commercial Demand")}
        value={commercialDemand}
        factors={commercialFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.IndustrialDemand, "Industrial Demand")}
        value={industrialDemand}
        factors={industrialFactors}
        t={t}
    />
    <DemandSection2
        title={t(Localekeys.OfficeDemand, "Office Demand")}
        value={officeDemand}
        factors={officeFactors}
        t={t}
    />
      
    </Panel>
  );
};

export default $DemandFactors;
